import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Nonce-based CSP (see src/proxy.ts) requires every page to be dynamically
// rendered: the nonce is generated fresh per request, so a statically
// prerendered page's inline scripts would carry a stale/missing nonce that
// never matches the CSP header of a later request, breaking hydration.
// Forcing it here in the root layout covers every route in the app.
export const dynamic = "force-dynamic";

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
